name: flutter_app_dio_and_json
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio:
  json_serializable:
  flutter_riverpod: ^0.12.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:

  uses-material-design: true

